version: '3.7'

services:
  nginx:
    image: registry.gitlab.com/lynx-team/docker/nginx:1.16
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80"

  php:
    image: registry.gitlab.com/lynx-team/docker/php:7.3
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_SECRET=${APP_SECRET}
      - PHP_CONF_MEMORY_LIMIT=98M
      - PHP_CONF_DISPLAY_ERRORS=On
      - PHP_CONF_DISPLAY_STARTUP_ERRORS=On
      - PHP_CONF_DISPLAY_HTML_ERRORS=On
      - PHP_CONF_XDEBUG_ENABLE=yes
      - PHP_CONF_XDEBUG_REMOTE_HOST="${DOCKER_IP}"
      - PHP_CONF_XDEBUG_REMOTE_PORT=9000
      - PHP_CONF_XDEBUG_IDEKEY=phpstorm
      - PHP_CONF_OPCACHE_ENABLE=yes
      - PHP_CONF_OPCACHE_VALIDATE_TIMESTAMPS_ENABLE=yes
      - PHP_CONF_FPM_POOL_CLEAR_ENV=no
      - PHP_IDE_CONFIG=serverName=sberbank-profile
      - USER_ID=${DOCKER_USER_ID}
      - GROUP_ID=${DOCKER_GROUP_ID}
    network_mode: service:nginx

  database:
    image: mariadb:10.4.2-bionic
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: 'sberbank_profile'
      MYSQL_USER: 'lynx'
      MYSQL_PASSWORD: 'lynx'
      MYSQL_ROOT_PASSWORD: 'root'

volumes:
  dbdata:
