# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\ProfileService:
        $adapters: !tagged { tag: 'app.adapter', index_by: 'key' }

    # --- Admin ---
    admin.bank:
        class: App\Admin\BankAdmin
        arguments:
            - ~
            - App\Entity\Bank
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Банк', group: 'Анкета' }

    admin.tariff:
        class: App\Admin\TariffAdmin
        arguments:
            - ~
            - App\Entity\Tariff
            - ~
            - !tagged { tag: 'app.adapter', default_index_method: 'getDefaultIndexName' }
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Тариф', group: 'Анкета' }

    admin.reception_range:
        class: App\Admin\ReceptionRangeAdmin
        arguments:
            - ~
            - App\Entity\ReceptionRange
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Прием на баковская карта/касса', group: 'Промежутки' }

    admin.extradition_range:
        class: App\Admin\ExtraditionRangeAdmin
        arguments:
            - ~
            - App\Entity\ExtraditionRange
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Выдача с банковской карты', group: 'Промежутки' }

    admin.transfer_range:
        class: App\Admin\TransferRangeAdmin
        arguments:
            - ~
            - App\Entity\TransferRange
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Перевод на физическое лицо', group: 'Промежутки' }

    admin.check_range:
        class: App\Admin\CheckRangeAdmin
        arguments:
            - ~
            - App\Entity\CheckRange
            - ~
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Выдача по чеку', group: 'Промежутки' }

    # --- Adapter ---

    # --- Alfa Bank ---
    App\Adapter\CommonAdapter:
        tags:
            - { name: 'app.adapter', key: 'App\Adapter\CommonAdapter' }
